# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycolor',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
