# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_category_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
