# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='categorycolor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorycolor',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product',
        ),
        migrations.DeleteModel(
            name='CategoryColor',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
