# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_categorycolor_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
